# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#                  Platform:    0 /    5 =   0.00%

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'platform' 

class TestPlatform < Test::Unit::TestCase
	def test_class_binary_dir
		assert_equal(AppConfig::RootDir + "/bin", Platform.binary_dir)
	end

	def test_class_home_dir
		assert_equal("#{ENV['HOME']}/.estelle", Platform.home_dir)
	end

	def test_class_os
		assert_equal(:osx, Platform.os)
	end

	def test_class_settings_file_path
		assert_equal("#{ENV['HOME']}/.estelle/settings.yaml", Platform.settings_file_path)
	end

	def test_class_which
		assert_equal(`which ls`, Platform.which("ls"))
	end
end

# Number of errors detected: 6
